### PR TITLE
Migrate to pyproject.toml and scikit-build-core

### PR DESCRIPTION
**Pull request by mochaaP**
Tested on py3.12/py3.10/py3.8/pypy3.10 Fedora Linux, py3.12 MSVC, py3.12 macOS 10.15

TODO:
- [x] use cibuildwheel
- [x] use <https://github.com/python/cpython-bin-deps/tree/tcltk> on win32 msvc

### CODE REVIEW

**Comment by mochaaP** [comment]
Snippet for testing:

```sh
cd tests
```

```python
import tkinter as tk
import tksvg

window = tk.Tk()
svg_image = tksvg.SvgImage(file="orb.svg")
label = tk.Label(image=svg_image)
label.pack()
window.mainloop()
```

**Comment by mochaaP** [comment]
prebuilt wheels: https://github.com/mcha-forks/python-tksvg/actions/runs/8100607697

**Comment by mochaaP** [comment]
cc @rdbende @RedFantom any interests in this?

**Comment by rdbende** [comment]
Yup, absolutely, this is amazing!
I'll find some time to review it. I'm not sure, when will @RedFantom have time to merge it though

**Comment by mochaaP** [comment]
Should I also make the same change to gttk?

**Comment by rdbende** [comment]
Actually, that would be awesome. I tried to tackle that multiple times, but always gave up. However that would make the project much more maintainable.

**Comment by mochaaP** [comment]
Nice! working on it. :)

**Review by rdbende — APPROVED** [review]
Looks/works well for me

**Comment by rdbende** [comment]
The new build system is definitely more straightforward and easier to maintain than the existing appveyor. In addition we will no longer have to backport every upstream change manually, as they are now submodules.

Many thanks for this!

**Comment by mochaaP** [comment]
Hmm, CI breaks on macos-14-arm64 `20240219.1` but not `20240116.1` due to a linkage error (target mismatch - needed arm64, presented arm64e)

**Comment by mochaaP** [comment]
Hmm, CI breaks on macos-14-arm64 `20240219.1` but not `20240116.1` due to a linkage error (target mismatch - needed arm64, presented arm64e)

Filed an issue here: https://github.com/actions/runner-images/issues/9441, will need further investigation

**Comment by mochaaP** [comment]
closes #3
supersedes #1 #4

**Review by rdbende — APPROVED** [review]
@RedFantom these changes look good to me. Could you take a look at it when you have a little free time?

**Pull request merged**
