### PR TITLE
Backport upstream changes

### PR DESCRIPTION
**Pull request by rdbende**
@RedFantom 

1. It would be nice if you enabled issues on this fork, so I don't need to make a pull request to ask something :D. I know at least two person who would have opened one.

2. It would be good to add a CI to build wheels with macOS binaries (I can work on that), because it's currently quite hard to install this on a mac. The upstream has also added a Github action to build binaries for various platforms.

### CODE REVIEW

**Comment by Moosems** [comment]
Would you also make a PR with better documentation?

**Comment by rdbende** [comment]
> Would you also make a PR with better documentation?

Actually, what's the issue with documentation? It's the same as `tkinter.PhotoImage` just named differently.

**Comment by Moosems** [comment]
The documentation didn't make it very clear that that's all it had :D.

**Comment by Moosems** [comment]
It said it was similar but how do I know the exact differences?

**Comment by Moosems** [comment]
I would mention that its actually built on top of the PhotoImage class and simply adds the functionality of svg's.

**Comment by RedFantom** [comment]
@rdbende : Okay, Issues are now enabled! Of course I would welcome a PR which adds automatic building for mac as well. 

Unfortunately since I built the CI system for this repository, Travis-CI changed their policy for open-source repositories, hence why it is no longer enabled. Perhaps this can also be migrated to the GitHub Actions system?

Currently I have very little time, as you have probably noticed 🙈 , so it is unlikely I will get around to it anytime soon. I'm not even sure how to prioritize the long todo-list at this point.

Regarding documentation, @Moosems , adding documentation with sphinx should be pretty trivial, but I didn't add it in the first place because indeed `SvgImage` has pretty much the same interface as `PhotoImage`. Do you think it would add something to have a (single) RTD page?

**Comment by Moosems** [comment]
I would simply make a piece in README and plain if the zoom and that it's quite literally built on top of the PhotoImage class. After that, I'd say it's documented sufficiently and any questions regarding the inner workings (tksvg) can be routed to the origin repo :D.

**Comment by Moosems** [comment]
@rdbende, Would we like to work on the builds?

**Comment by rdbende** [comment]
What do you mean under "we"? Me or you? lol
I do plan to work on it, but not now.

**Comment by Moosems** [comment]
I would like to help on it, I simply need a basic introduction :D.

**Comment by Moosems** [comment]
Pacman seems to be causing a lot of problems, I'll look into that a bit.

**Comment by Moosems** [comment]
Pacman can be completely removed, in fact, the appveyor CI should just become a GH action.

**Comment by Moosems** [comment]
Looking at the appveyor, why the flip does it even exist?

**Comment by rdbende** [comment]
> Unfortunately since I built the CI system for this repository, Travis-CI changed their policy for open-source repositories, hence why it is no longer enabled. Perhaps this can also be migrated to the GitHub Actions system?

**Comment by Moosems** [comment]
But whats the point of the CI?

**Comment by Moosems** [comment]
The only CI on the original is [build_xplat](https://github.com/oehhar/tksvg/blob/master/.github/workflows/build_xplat.yml) so we could just remove it :D.

**Comment by Moosems** [comment]
@rdbende What actions need to stay?

**Comment by rdbende** [comment]
I think only the Pypi publisher one.
Then we would need 3 GHAs:
- Run unittests with Nose
- Build binaries
- Publish to Pypi

**Comment by Moosems** [comment]
So delete the appveyor and update the others?

**Comment by rdbende** [comment]
I also think you should separate it to PRs. One for the builds, and one for the test and Pypi stuff.

**Comment by RedFantom** [comment]
> Looking at the appveyor, why the flip does it even exist?

I am used to using AppVeyor / MSYS2 for building Windows-compatible binaries. If you have an idea for setting up a build system using VC++ on GitHub Actions, feel free to open a PR / issue with some details on how to include and link the Tcl and Tk development files.

GitHub Actions already builds Linux binaries, but is not yet used for CI. That is something which could be addressed in another PR.

If this PR has the CI-related stuff removed (force-push is acceptable to me) and PR #4 is merged, then we can merge this one too.

**Comment by rdbende** [comment]
Superseeded by #6

**Pull request closed without merging**
